version: 2

jobs:
  build:
    docker:
      - image: loganyott/php:7-xdebug
    working_directory: ~/qtx
    steps:
      - checkout
      - restore_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
      - run: composer install -on --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - run: ./vendor/bin/phpunit --coverage-clover=clover.xml
      - run: bash <(curl -s https://codecov.io/bash) -s ~/qtx
      - run: ./vendor/bin/phpcs --config-set installed_paths $HOME/qtx/vendor/wp-coding-standards/wpcs
      - run: ./vendor/bin/phpcs --config-set ignore_errors_on_exit 1
      - run: ./vendor/bin/phpcs --config-set ignore_warnings_on_exit 1
      - run: ./vendor/bin/phpcs --standard=WordPress --ignore=vendor ./
